<a href="https://colab.research.google.com/github/Nishikata08/Sentiment-Analysis---Major-Project/blob/main/Major_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Re_Data.csv')
df.iloc[0:5000]

clean_comment  category
0      family mormon have never tried explain them t...  Positive
1     buddhism has very much lot compatible with chr...  Positive
2     seriously don say thing first all they won get...  Negative
3     what you have learned yours and only yours wha...   Neutral
4     for your own benefit you may want read living ...  Positive
...                                                 ...       ...
4995      this has been enlightening cultural exchange   Positive
4996           dont even belong here but this much fun   Positive
4997   the whiskey this really out left field clint ...  Positive
4998  aaron barrett performance tonight related this...   Neutral
4999                                    flair thenewse    Neutral

[5000 rows x 2 columns]

In [32]:
df.dropna(inplace=True)

In [33]:
import string
df['clean_comment'] = df['clean_comment'].str.replace('[^\w\s]','')
df.clean_comment = df.clean_comment.str.replace('\d+','')

In [34]:
x = df.iloc[:,0]
y = df.iloc[:,1]

In [35]:
df['category'].value_counts()

Positive    4871
Neutral     3599
Negative    2503
Name: category, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [37]:
import numpy as np

In [38]:
np.unique(y_train,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([1744, 2538, 3399]))

In [39]:
np.unique(y_test,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 759, 1061, 1472]))

In [40]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

In [41]:
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', d

In [42]:
y_pred = text_model.predict(x_test)
y_pred

array(['Neutral', 'Positive', 'Positive', ..., 'Neutral', 'Positive',
       'Neutral'], dtype=object)

In [43]:
np.unique(y_pred,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 333, 1235, 1724]))

In [44]:
y_test

array(['Positive', 'Positive', 'Positive', ..., 'Neutral', 'Neutral',
       'Negative'], dtype=object)

In [45]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [46]:
accuracy_score(y_pred,y_test)*100

74.87849331713244

In [47]:
confusion_matrix(y_pred,y_test)

array([[ 277,   19,   37],
       [ 160,  914,  161],
       [ 322,  128, 1274]])

In [48]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

    Negative       0.36      0.83      0.51       333
     Neutral       0.86      0.74      0.80      1235
    Positive       0.87      0.74      0.80      1724

    accuracy                           0.75      3292
   macro avg       0.70      0.77      0.70      3292
weighted avg       0.81      0.75      0.77      3292



In [49]:
text_model.predict(["The room was kind of clean but had a VERY strong smell of dogs Generally below average but ok for a overnight stay if youre not too fussy Would consider staying again if the price was right Breakfast was free and just about better than nothing"])

array(['Positive'], dtype=object)

In [53]:
!pip install streamlit
!pip install pyngrok==4.1.1
from pyngrok import ngrok
!pip install emoji

     |████████████████████████████████| 133kB 4.2MB/s 


In [65]:
%%writefile app.py
import streamlit as st
st.title('Sentiment Analysis')
import pandas as pd
import emoji
df = pd.read_csv('/content/drive/MyDrive/Re_Data.csv')
df =df.iloc[0:5000]
df.dropna(inplace=True)
import string
df['clean_comment'] = df['clean_comment'].str.replace('[^\w\s]','')
df.clean_comment = df.clean_comment.str.replace('\d+','')
x = df.iloc[:,0]
y = df.iloc[:,1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x_train, y_train)
select = st.text_input('Enter your message')
op = text_model.predict([select])
if op[0] == "Positive":
  st.title(op)
  st.title(emoji.emojize(':smile:'))
elif op[0]=="Neutral":
  st.title(op)
  st.title(emoji.emojize(':expressionless:'))
elif op[0]=="Negative":
  st.title(op)
  st.title(emoji.emojize(':worried:'))

Overwriting app.py


In [52]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://3dfb2afd033c.ngrok.io'